export const iconOptions = [
  { label: "None", value: "" },
  { label: "Tina", value: "Tina" },
  { label: "Bookmark", value: "BiBookmark" },
  { label: "Check", value: "BiCheck" },
  { label: "Chevron Down", value: "BiChevronDown" },
  { label: "Chevron Left", value: "BiChevronLeft" },
  { label: "Chevron Right", value: "BiChevronRight" },
  { label: "Chevron Up", value: "BiChevronUp" },
  { label: "Download", value: "BiDownload" },
  { label: "External Link", value: "BiLinkExternal" },
  { label: "Eye (Lucide)", value: "Eye" },
  { label: "Facebook", value: "FaFacebookF" },
  { label: "Git Branch", value: "BiGitBranch" },
  { label: "Git Branch (Lucide)", value: "GitBranch" },
  { label: "GitHub", value: "FaGithub" },
  { label: "Heart", value: "BiHeart" },
  { label: "Home", value: "BiHome" },
  { label: "Instagram", value: "AiFillInstagram" },
  { label: "Link", value: "BiLink" },
  { label: "LinkedIn", value: "FaLinkedin" },
  { label: "Minus", value: "BiMinus" },
  { label: "Package", value: "BiPackage" },
  { label: "Package Open (Lucide)", value: "PackageOpen" },
  { label: "Plus", value: "BiPlus" },
  { label: "Search", value: "BiSearch" },
  { label: "Settings", value: "BiCog" },
  { label: "Star", value: "BiStar" },
  { label: "Twitter", value: "FaXTwitter" },
  { label: "Upload", value: "BiUpload" },
  { label: "User", value: "BiUser" },
  { label: "YouTube", value: "FaYoutube" },
];
